### PR TITLE
Add Shearing;

### PR DESCRIPTION
**Pull request by cjbrigato**
Add Shearing transform matrix, alongside required direction (as enum class, arguable).

### CODE REVIEW

**Comment by thedmd** [comment]
First of all, thank you for PR.

I think I would like to go in the direction of adding function:
```cpp
ImMatrix Shear(float x, float y);
```

Passing scaling factors is better understood than angles. Also matches not only behavior of different libraries but also [Shear_matrix](https://en.wikipedia.org/wiki/Shear_matrix). To replicate behavior of proposed `Shearing` functions, a call will look like:
```cpp
Shear(tanf(angle), 0.0f); // for X axis
Shear(0.0f, tanf(angle)); // for Y axis
```

I would accept PR with that form.

**Comment by cjbrigato** [comment]
Hi,
indeed, this would be way better implementation and friendly usage.
I'm much rusty when it comes to working with matrices, thing I did not do since age. So also thanks for pointing me to proper literature. Will do as requested.

**Comment by cjbrigato** [comment]
One question however, you propose `Shear` as function name, yet you actually implemented `Scaling `and `Rotation`.
I chose shearing to keep with consistency. Should this consistency be broken ?

Edit : unless mistaken, shearing function is now as requested.

**Comment by thedmd** [comment]
Functions are called `Translation`, `Rotation` and `Scaling` just because there are translation matrix, rotation matrix and scaling matrix. English is consistent. 🙃

There is also shear matrix, hence `Shear` function name.

**Comment by thedmd** [comment]
~~Aren't X and Y swapped around in the shear implementation?~~

They are correct.

**Comment by cjbrigato** [comment]
Sorry, English is far away from being my native, I'm doing my best. Also, 

> Naming things is hard

 ;)

**Comment by thedmd** [comment]
I added `Shear` matching what we had discussed. Also added one accepting ImVec2.

I had it tested.

Thank you for PR!

**Comment by cjbrigato** [comment]
My pleasure

**Comment by thedmd** [comment]
I just rebased this branch on master, to get rid of conflicts. (_FringeScale was introduced to ImDrawList on master, which touched same code as this branch).

**Pull request closed without merging**
